fixes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -131,7 +131,7 @@ jobs:
         with:
           name: sbom.cyclonedx
 
-      - name: ORAS Setup & Push SBOM reports to GitHub Container Registry
+      - name: ORAS Setup
         #if: github.ref == 'refs/heads/release'
         run: |
           ORAS_VERSION="v0.8.1"
@@ -142,10 +142,17 @@ jobs:
           ./oras_install/oras push ghcr.io/${{github.repository_owner}}/retraced-js/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*
           cd ..
 
-      - name: Sign the sbom images
+      - name: Push SBOM reports to GitHub Container Registry & Sign the sbom images
         #if: github.ref == 'refs/heads/release'
         run: |
-          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository_owner}}/retraced-js/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }}
+          result=$(./oras_install/oras push ghcr.io/${{github.repository_owner}}/retraced-js/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*)
+          ORAS_DIGEST=$(echo $result | grep -oE 'sha256:[a-f0-9]{64}')
+          if [ -z "$ORAS_DIGEST" ]; then
+            echo "Error: ORAS_DIGEST is empty"
+            exit 1
+          fi
+          cd ..
+          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository_owner}}/retraced-js/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}@ORAS_DIGEST
         env:
           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
 
