Using ORAS digest & beta tags in Github action (#85)
* fix

* fixes

* fix

* fix

* fiix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,6 +23,7 @@ jobs:
     outputs:
       NPM_VERSION: ${{ steps.version.outputs.NPM_VERSION }}
       PUBLISH_TAG: ${{ steps.version.outputs.PUBLISH_TAG }}
+      IMAGE_SUFFIX: ${{ steps.version.outputs.IMAGE_SUFFIX }}
     strategy:
       matrix:
         node-version: [18.x]
@@ -44,6 +45,7 @@ jobs:
           RETRACED_VERSION=$(echo $(cat ./package.json) | json version)
 
           publishTag="latest"
+          imageSuffix=""
 
           if [[ "$GITHUB_REF" == *\/release ]]
           then
@@ -51,11 +53,13 @@ jobs:
           else
             echo "Dev branch"
             publishTag="beta"
+            imageSuffix="-beta"
             RETRACED_VERSION="${RETRACED_VERSION}-beta.${GITHUB_RUN_NUMBER}"
           fi
 
           echo "NPM_VERSION=${RETRACED_VERSION}" >> $GITHUB_OUTPUT
           echo "PUBLISH_TAG=${publishTag}" >> $GITHUB_OUTPUT
+          echo "IMAGE_SUFFIX=${imageSuffix}" >> $GITHUB_OUTPUT
 
   build:
     needs: ci
@@ -65,6 +69,7 @@ jobs:
         uses: actions/checkout@v3
 
       - run: echo ${{ needs.ci.outputs.NPM_VERSION }}
+      - run: echo ${{ needs.ci.outputs.IMAGE_SUFFIX }}
 
       - name: Get short SHA
         id: slug
@@ -125,7 +130,7 @@ jobs:
         with:
           name: sbom.cyclonedx
 
-      - name: ORAS Setup & Push SBOM reports to GitHub Container Registry
+      - name: ORAS Setup
         if: github.ref == 'refs/heads/release'
         run: |
           ORAS_VERSION="v0.8.1"
@@ -133,13 +138,20 @@ jobs:
           curl -LO "https://github.com/oras-project/oras/releases/download/${ORAS_VERSION}/${ORAS_FILENAME}"
           mkdir oras_install
           tar -xvf "${ORAS_FILENAME}" -C oras_install
-          ./oras_install/oras push ghcr.io/${{github.repository_owner}}/retraced-js/sbom:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*
+          ./oras_install/oras push ghcr.io/${{github.repository}}/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*
           cd ..
 
-      - name: Sign the sbom images
+      - name: Push SBOM reports to GitHub Container Registry & Sign the sbom images
         if: github.ref == 'refs/heads/release'
         run: |
-          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository_owner}}/retraced-js/sbom:npm-${{ needs.ci.outputs.NPM_VERSION }}
+          result=$(./oras_install/oras push ghcr.io/${{github.repository}}/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*)
+          ORAS_DIGEST=$(echo $result | grep -oE 'sha256:[a-f0-9]{64}')
+          if [ -z "$ORAS_DIGEST" ]; then
+            echo "Error: ORAS_DIGEST is empty"
+            exit 1
+          fi
+          cd ..
+          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository}}/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}@${ORAS_DIGEST}
         env:
           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
 
